name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test   # ensures CI passes first

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Login to GitHub Container Registry
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Build Docker image
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      # 4. Push image
      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:latest

      # 5. Deploy via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker network create statuspulse-net || true
            
            docker pull ghcr.io/${{ github.repository }}:latest

            docker stop statuspulse-app statuspulse-caddy || true
            docker rm statuspulse-app statuspulse-caddy || true

            # Run the FastAPI app
            docker run -d --name statuspulse-app --network statuspulse-net -p 8000:8000 ghcr.io/${{ github.repository }}:latest

            # Create Caddyfile on the server
            cat << 'EOF' > Caddyfile
            34.222.238.103.nip.io {
                reverse_proxy statuspulse-app:8000
            }
            EOF

            # Run Caddy reverse proxy
            docker run -d --name statuspulse-caddy --network statuspulse-net -p 80:80 -p 443:443 -v $(pwd)/Caddyfile:/etc/caddy/Caddyfile -v caddy_data:/data -v caddy_config:/config caddy:2-alpine

            sleep 10
            curl -f http://localhost:8000/health || exit 1